name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: Cypress
    steps:
      - uses: actions/checkout@v1

      - run: ls -l
      - run: yarn install

      - run: ls -l
      - run: yarn build

      - run: ls -l

      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
